### ISSUE TITLE
Using variables ?

### ISSUE THREAD

**Issue by EvannG1** [CreativeCraft/bungeejoinmotd#3]
Hello,

I would like to use your plugin on my server, but I would like to know how to use variables to display a message like : 
Hello %player%, you are currently the on the world %world%

Is this currently possible?

**Comment by Log1x** [comment]
great suggestion! although to note, the plugin only displays the MOTD on initial proxy connect.

nonetheless, i can definitely do this.

do you have some suggestions on a list of variables that should be added?

**Comment by EvannG1** [comment]
In my case, I have disabled the force\_default\_server, so it could be useful to be able to display a message with the name of the world/server where you spawned when you connect.  
Otherwise, being able to display the name of the player seems to me to be one of the most important values to implement.  
Other variables that could be useful :  
\- Time in game  
\- Number of players connected on the current world/server  
\- Number of players connected on the whole network

**Comment by Log1x** [comment]
Posted a resource update for 1.0.4 on [Spigot](https://www.spigotmc.org/resources/bungeejoinmotd.99305/). Let me know if  you have any other suggestions.

**Comment by Log1x** [comment]
scratch that I broke something. will fix when I can. stay using 1.0.3.
